# Site settings
title: William Harvey Designs
email: letstalk@williamharveydesigns.com
description: "Designing engaging Mobile/Web UI/UX solutions for your users"
info: "A Mobile/Web UI/UX Design Portfolio"
message: "Designing engaging Mobile/Web UI/UX solutions for your users"
keywords: "San Diego,California,mac,apple,iphone,ios,osx,design,app,UI,UX,product,mobile,web,freelance,consultant,branding,project management,prototyping,IxD,interaction,motion,animation,presentation"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.williamharveydesigns.com" # the base hostname & protocol for your site
twitter_username: 
# Build settings
markdown: kramdown
author:
    name: William Harvey
    twitter: 
    url: http://www.williamharveydesigns.com
    header_bg: /images/profile-header.png
    avatar: /images/avatar.jpg
    email: letstalk@williamharveydesigns.com
facebook: 
    image: